"""Initial Migration

Revision ID: 21839d578108
Revises: 78280d665a90
Create Date: 2021-03-08 00:22:38.770274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21839d578108'
down_revision = '78280d665a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('pizza_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'pizzas', ['pizza_id'], ['id'])
    op.drop_constraint('pizzas_order_id_fkey', 'pizzas', type_='foreignkey')
    op.drop_column('pizzas', 'order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pizzas', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pizzas_order_id_fkey', 'pizzas', 'pizzas', ['order_id'], ['id'])
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'pizza_id')
    # ### end Alembic commands ###
