"""Initial Migration

Revision ID: 28e9c4d23c5a
Revises: 9465bc41d65d
Create Date: 2021-03-07 00:03:01.155418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e9c4d23c5a'
down_revision = '9465bc41d65d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'order_id')
    # ### end Alembic commands ###
