"""Initial Migration

Revision ID: 34602d8c5d3a
Revises: 3e6ce6efb098
Create Date: 2021-03-07 02:40:00.731965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34602d8c5d3a'
down_revision = '3e6ce6efb098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('size', sa.String(length=255), nullable=True),
    sa.Column('toppings', sa.String(length=255), nullable=True),
    sa.Column('no_of_pizzas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_email'), 'orders', ['email'], unique=False)
    op.create_index(op.f('ix_orders_no_of_pizzas'), 'orders', ['no_of_pizzas'], unique=False)
    op.create_index(op.f('ix_orders_size'), 'orders', ['size'], unique=False)
    op.create_index(op.f('ix_orders_toppings'), 'orders', ['toppings'], unique=False)
    op.create_table('pizzas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('pic_path', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('price_large', sa.Integer(), nullable=True),
    sa.Column('price_small', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('pass_secure', sa.String(length=255), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('pizzas')
    op.drop_index(op.f('ix_orders_toppings'), table_name='orders')
    op.drop_index(op.f('ix_orders_size'), table_name='orders')
    op.drop_index(op.f('ix_orders_no_of_pizzas'), table_name='orders')
    op.drop_index(op.f('ix_orders_email'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
