"""Initial Migration

Revision ID: 3b31a29a67c5
Revises: 5087d2625874
Create Date: 2021-03-05 10:01:03.111058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b31a29a67c5'
down_revision = '5087d2625874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('size', sa.String(length=255), nullable=True),
    sa.Column('toppings', sa.String(length=255), nullable=True),
    sa.Column('no_of_pizzas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_email'), 'order', ['email'], unique=False)
    op.create_index(op.f('ix_order_no_of_pizzas'), 'order', ['no_of_pizzas'], unique=False)
    op.create_index(op.f('ix_order_size'), 'order', ['size'], unique=False)
    op.create_index(op.f('ix_order_toppings'), 'order', ['toppings'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('pass_secure', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('pizza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pizza_title', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pizza')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index(op.f('ix_order_toppings'), table_name='order')
    op.drop_index(op.f('ix_order_size'), table_name='order')
    op.drop_index(op.f('ix_order_no_of_pizzas'), table_name='order')
    op.drop_index(op.f('ix_order_email'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
