"""Initial Migration

Revision ID: 3e6ce6efb098
Revises: 68121abb05d6
Create Date: 2021-03-07 02:33:00.807984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e6ce6efb098'
down_revision = '68121abb05d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pizzas', sa.Column('price_large', sa.Integer(), nullable=True))
    op.add_column('pizzas', sa.Column('price_small', sa.Integer(), nullable=True))
    op.drop_column('pizzas', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pizzas', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pizzas', 'price_small')
    op.drop_column('pizzas', 'price_large')
    # ### end Alembic commands ###
