"""Initial Migration

Revision ID: 5b158ea06ec0
Revises: f96cd0e6345b
Create Date: 2021-03-05 11:56:23.454424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b158ea06ec0'
down_revision = 'f96cd0e6345b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pizza', sa.Column('pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pizza', 'pic_path')
    # ### end Alembic commands ###
