"""Initial Migration

Revision ID: 68121abb05d6
Revises: 906c9159ecce
Create Date: 2021-03-07 01:13:53.388936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68121abb05d6'
down_revision = '906c9159ecce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pizzas', sa.Column('pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pizzas', 'pic_path')
    # ### end Alembic commands ###
