"""Initial Migration

Revision ID: 78280d665a90
Revises: 34602d8c5d3a
Create Date: 2021-03-08 00:15:54.050631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78280d665a90'
down_revision = '34602d8c5d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pizzas', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pizzas', 'pizzas', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pizzas', type_='foreignkey')
    op.drop_column('pizzas', 'order_id')
    # ### end Alembic commands ###
