"""Initial Migration

Revision ID: 906c9159ecce
Revises: 28e9c4d23c5a
Create Date: 2021-03-07 00:45:58.923586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906c9159ecce'
down_revision = '28e9c4d23c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pizzas', 'pic_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pizzas', sa.Column('pic_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
