"""Initial Migration

Revision ID: 9465bc41d65d
Revises: a8ebf051ea8a
Create Date: 2021-03-05 14:41:13.402418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9465bc41d65d'
down_revision = 'a8ebf051ea8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('size', sa.String(length=255), nullable=True),
    sa.Column('toppings', sa.String(length=255), nullable=True),
    sa.Column('no_of_pizzas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_email'), 'orders', ['email'], unique=False)
    op.create_index(op.f('ix_orders_no_of_pizzas'), 'orders', ['no_of_pizzas'], unique=False)
    op.create_index(op.f('ix_orders_size'), 'orders', ['size'], unique=False)
    op.create_index(op.f('ix_orders_toppings'), 'orders', ['toppings'], unique=False)
    op.drop_index('ix_order_email', table_name='order')
    op.drop_index('ix_order_no_of_pizzas', table_name='order')
    op.drop_index('ix_order_size', table_name='order')
    op.drop_index('ix_order_toppings', table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('size', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('toppings', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('no_of_pizzas', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='order_pkey')
    )
    op.create_index('ix_order_toppings', 'order', ['toppings'], unique=False)
    op.create_index('ix_order_size', 'order', ['size'], unique=False)
    op.create_index('ix_order_no_of_pizzas', 'order', ['no_of_pizzas'], unique=False)
    op.create_index('ix_order_email', 'order', ['email'], unique=False)
    op.drop_index(op.f('ix_orders_toppings'), table_name='orders')
    op.drop_index(op.f('ix_orders_size'), table_name='orders')
    op.drop_index(op.f('ix_orders_no_of_pizzas'), table_name='orders')
    op.drop_index(op.f('ix_orders_email'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
