"""Initial Migration

Revision ID: f96cd0e6345b
Revises: 3b31a29a67c5
Create Date: 2021-03-05 11:37:00.666651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f96cd0e6345b'
down_revision = '3b31a29a67c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pizza', sa.Column('name', sa.String(), nullable=True))
    op.add_column('pizza', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('pizza', sa.Column('size', sa.String(), nullable=True))
    op.drop_constraint('pizza_user_id_fkey', 'pizza', type_='foreignkey')
    op.drop_column('pizza', 'image_path')
    op.drop_column('pizza', 'user_id')
    op.drop_column('pizza', 'description')
    op.drop_column('pizza', 'pizza_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pizza', sa.Column('pizza_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pizza', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pizza', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pizza', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('pizza_user_id_fkey', 'pizza', 'users', ['user_id'], ['id'])
    op.drop_column('pizza', 'size')
    op.drop_column('pizza', 'price')
    op.drop_column('pizza', 'name')
    # ### end Alembic commands ###
